openapi: 3.0.0

title: task REST Web Service for task System Group Project / Bob Trieste
description:
    Task RESTfull Web Service is used to access and modify tasks in the
    task Database and an Ads in the Note Database.
version: 0.0.1
servers:
  - url: 'http://localhost:6107'
    description: adserver-service
paths:
  /ad:
    get:
      summary: serve an ad from the local host adserver-service
      responses:
        '200':
          description: A list of ads
          content:
            array:
              schema:
                type: string
