openapi: 3.0.0
info:
  title: Quote API
  description: >-
    A simple web service that delivers words and quotes and answers questions. Bob Trieste
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
paths:
  /quote:
    get:
      summary: Serves up quotes
#      responses:
#       '200':
#         description: An array of quote objects
      responses:
        '201':
          description: A quote object
          content:
            application/json:
              schema:
                # we are referencing the quote object definition found at the bottom of the file
                $ref: '#/components/schemas/Quotes'
        '422':
          description: Incomplete, some required fields missing.
  /word:
    get:
      summary: word-of-the-day.
      responses:
        '200':
          description: Word object for day.
          content:
            application/json:
              schema:
                # we are referencing the City object definition found at the bottom of the file
                $ref: '#/components/schemas/Definition'
        '422':
          description: word could not be found
  /magic:
    post:
      summary: answer-to-your-question.
      responses:
        '200':
          description: answer object matching given question.
          content:
            application/json:
              schema:
                # we are referencing the City object definition found at the bottom of the file
                $ref: '#/components/schemas/Answer'
        '422':
          description: word could not be found
# This section defines the QuoteWordAnswer object that goes back and forth as JSON
components:
  schemas:
    Quotes:
      properties:
        author:
          type: string
        quote:
          type: string
      required:
        - author
        - quote
    Definition:
      properties:
        word:
          type: string
        definition:
          type: string
      required:
        - word
        - definition
    Answer:
      properties:
        question:
          type: string
        answer:
          type: string
      required:
        - question
        - answer
